### PR TITLE
Changing value error output 

### PR DESCRIPTION
**Pull request by gwenwhite**
Fixing issue #14

### CODE REVIEW

**Comment by gwenwhite** [comment]
It appears the checks are failing for the same reason that they are on pull request #22. Not sure how to fix this issue.

**Comment by jennyfothergill** [comment]
It looks like we may have some tangled git history here. I'm noticing some commits from Chris' pymbar PR and your other PR. Basically we want to replay the changes in commit 2701ce4 onto the current master branch. I think we can do this with git cherry-pick:
```
git checkout master 
git pull upstream master
git checkout -b mynewbranch
git cherry-pick 2701ce4
```
Then you can open a PR with this new branch. @erjank may have a better suggestion. My worry with the current history is deleting the sampler.py file may cause issues when Chris tries to merge it in.

**Comment by jennyfothergill** [comment]
Closed in favor of #26

**Comment by erjank** [comment]
I don't have a better suggestion in my quick skimming. Thank you both for cleaning up my mess! Bad advisor! Bad!

**Pull request closed without merging**
