### PR TITLE
Rename function

### PR DESCRIPTION
**Pull request by gwenwhite**
Changed snap_molecule_cluster to get_molecule_cluster to resolve issue #13

### CODE REVIEW

**Review by erjank — CHANGES_REQUESTED** [review]
Update deprecated calls to "snap_molecule_cluster" in structure.py and test_gsd.py

**Review by jennyfothergill — CHANGES_REQUESTED** [review]
Nice work! I see one more instance to change in `cmeutils/structure.py` [on line 167](https://github.com/cmelab/cmeutils/blob/adb17643140ee72bb7e7efe67139f3b286659f9a/cmeutils/structure.py#L167)

**Review by jennyfothergill — APPROVED** [review]
LGTM!

**Review by erjank — APPROVED** [review]
Looks good to me.

**Pull request merged**
